### ISSUE TITLE
Add json5 support

### ISSUE THREAD

**Issue by luca-trigili** [bennycode/linessorterplus#5]
https://github.com/bennycode/linessorterplus/blob/2c03f80ab42160fb4e5b24623b06bb76456c2ab0/src/com/bennycode/linessorterplus/SortAction.java#L40

This line should be changed to work with json5 that support comments & more

Thanks for the plugin

**Comment by bennycode** [comment]
Hi @luca-trigili, would it mean just to also check for `.json5` or is there another extension?

**Comment by luca-trigili** [comment]
Accordingly to https://json5.org/ and https://en.wikipedia.org/wiki/JSON#Supersets we should be fine

**Comment by bennycode** [comment]
Ok. Would you mind making a PR for it? I can then merge it and create a new build. ☺️ I know that there is also `.jsonc` which should be included ([source](https://changelog.com/news/jsonc-is-a-superset-of-json-which-supports-comments-6LwR)). Maybe a wildcard like "ends with `*.json*`" will wok.

**Comment by luca-trigili** [comment]
Done

**Comment by bennycode** [comment]
Thank you for making a PR! 😊 Really happy that this plugin is still useful after 2 years. I just uploaded v1.2.0 to the JetBrains Marketplace. Once approved, which can take up to 2 business days, it will be publicly available for download.
